language: go

go:
  - 1.9

before_install:
  - sudo add-apt-repository -y ppa:masterminds/glide
  - sudo apt-get update -qq
  - sudo apt-get install -qq glide

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

install:
  - glide up

script:
  - make test